import Head from 'next/head';
import { signIn, useSession } from 'next-auth/react';
import { useEffect, useState } from 'react';
import Player from '@/components/player';
import Menu from '@/components/menu';
import Loading from '@/components/loading';
import packageJson from '/package.json';

export default function Home() {
	const { data: session, status } = useSession();

	const [isLoading, setIsLoading] = useState(false);
	const [playlists, setPlaylists] = useState({});

	useEffect(() => {
		setIsLoading(true);
		const fetchData = async () => {
			try {
				const response = await fetch('/api/playlist');
				const playlistsData = await response.json();
				setPlaylists(playlistsData);
				setIsLoading(false);
			} catch (error) {
				console.error('Error fetching audio data:', error);
			}
		};

		fetchData();
	}, []);

	if (status == 'loading' || status == 'unauthenticated' || isLoading) {
		return <Loading status={isLoading ? 'loading' : status} />;
	}

	useEffect(() => {
		if (packageJson && packageJson.version && packageJson.version != session.user.version) {
			router.push('/auth/signin?callbackUrl=' + router.asPath);
		}
	});

	return (
		<>
			<Head>
				<title>Music</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="stylesheet" href="index.css" />
				<link href="https://fonts.googleapis.com/css2?family=Anta&family=Bebas+Neue&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
			</Head>
			<main className="w-screen h-screen">
				<div className="w-full h-full relative flex overflow-hidden bg-[#171719]">
					<Player songId={'0dea8019-26ff-49b1-b704-c89a78a5c6da'} />
					<Menu />
					<div className="w-full h-full overflow-hidden">
						<div className="w-full p-7 pb-0">
							<h1 class=" text-3xl mb-0 font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl lg:text-6xl dark:text-white">Playlists</h1>
							<p class="mb-6 text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400">Yours playlists</p>
						</div>
						<div className="px-7">
							<div class="relative overflow-x-auto">
								<table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
									<thead class="text-xs text-gray-900 uppercase dark:text-gray-400">
										<tr>
											<th scope="col" class="px-6 py-3">
												Product name
											</th>
											<th scope="col" class="px-6 py-3">
												Color
											</th>
											<th scope="col" class="px-6 py-3">
												Category
											</th>
											<th scope="col" class="px-6 py-3">
												Price
											</th>
										</tr>
									</thead>
									<tbody>
										<tr class="bg-white dark:bg-gray-800">
											<th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
												Apple MacBook Pro 17"
											</th>
											<td class="px-6 py-4">Silver</td>
											<td class="px-6 py-4">Laptop</td>
											<td class="px-6 py-4">$2999</td>
										</tr>
										<tr class="bg-white dark:bg-gray-800">
											<th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
												Microsoft Surface Pro
											</th>
											<td class="px-6 py-4">White</td>
											<td class="px-6 py-4">Laptop PC</td>
											<td class="px-6 py-4">$1999</td>
										</tr>
										<tr class="bg-white dark:bg-gray-800">
											<th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
												Magic Mouse 2
											</th>
											<td class="px-6 py-4">Black</td>
											<td class="px-6 py-4">Accessories</td>
											<td class="px-6 py-4">$99</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
