version: '3.8'

networks:
    traefik_network:
        external: true
        name: traefik_network
    db_network:
        driver: bridge

services:
    music_db:
        image: mysql:latest
        restart: always
        container_name: musicDB
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3301:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - .env
        command: --max_connections=100000000
        networks:
            - db_network

    music_web:
        image: node:hydrogen-slim
        container_name: music
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - 3300:80
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
        networks:
            - traefik_network
            - db_network
        labels:
            - traefik.enable=true
            - traefik.http.routers.music_web.rule=Host(`music.server.com`)
            - traefik.http.routers.music_web.entrypoints=web
            - traefik.http.services.music_web.loadbalancer.server.port=80
            - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
            - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
            - traefik.http.routers.mywhoami.middlewares=mywwwredirect
