services:
    music_v3_db:
        image: mongo
        restart: always
        container_name: musicV3DB
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_USER_USERNAME: ${MONGO_USER_USERNAME}
            MONGO_INITDB_USER_PASSWORD: ${MONGO_USER_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        ports:
            - 27023:27017
        volumes:
            - ./data/mongo:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

    music_v3_web:
        image: node:hydrogen-slim
        container_name: musicV3
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - 4200:3000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
