import Head from 'next/head';
import { signIn, useSession } from 'next-auth/react';
import { useState } from 'react';
import Player from '@/components/player';
import Menu from '@/components/menu';
import { Router, useRouter } from 'next/router';

export default function Home() {
	const { data: session, status } = useSession();
	const router = useRouter();

	const [isLoading, setIsLoading] = useState(false);
	const [songId, setSongId] = useState();

	if (status == 'loading' || isLoading) {
		return (
			<>
				<Head>
					<title>Music</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
					<link rel="stylesheet" href="index.css" />
					<link href="https://fonts.googleapis.com/css2?family=Anta&family=Bebas+Neue&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
				</Head>
				<main className="w-full">loading</main>
			</>
		);
	}

	// if (status == 'unauthenticated') {
	// 	router.push('/auth/signin');
	// }

	return (
		<>
			<Head>
				<title>Music</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="stylesheet" href="index.css" />
				<link href="https://fonts.googleapis.com/css2?family=Anta&family=Bebas+Neue&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
			</Head>
			<main className="w-screen h-screen">
				<div className="w-full h-full relative overflow-hidden bg-[#171719]">
					<Menu />
					<Player songId={songId} setSongId={setSongId} />

					<div className="w-[1200px] h-[1119px] absolute left-60 top-0 overflow-hidden">
						<div className="flex flex-col justify-start items-center w-[1200px] absolute left-0 top-[91px] gap-6 pb-32">
							<div className="flex-grow-0 flex-shrink-0 w-[1156px] h-[464px] relative overflow-hidden">
								<div className="w-[1104px] h-[38px] absolute left-8 top-0 overflow-hidden">
									<p className="absolute left-0 top-1.5 text-lg font-semibold text-left text-[#fcfcfc]">Section Title</p>
									<div className="flex justify-center items-center w-6 absolute left-[1104px] top-8 p-1 rounded-[999px] bg-[#1f1f22] border border-[#ebebff]/5">
										<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
											<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
												<path d="M6.00001 13.2L11.2 7.99995L6.00001 2.79995" stroke="#FCFCFC" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
											</svg>
										</div>
									</div>
									<div className="flex justify-center items-center w-6 absolute left-[1048px] top-2 opacity-60 p-1 rounded-[999px] bg-[#1f1f22] border border-[#ebebff]/5">
										<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
											<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
												<path d="M9.99999 2.80005L4.79999 8.00005L9.99999 13.2" stroke="#FCFCFC" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
											</svg>
										</div>
									</div>
								</div>
								<div className="w-[2208px] h-[383px] absolute left-8 top-[45px]">
									<div className="w-[255px] h-[375px] absolute left-0 top-0 overflow-hidden rounded-lg" style={{ filter: 'drop-shadow(0px 8px 28px rgba(0,0,0,0.4))' }}>
										<div className="w-[255px] h-[257px] absolute left-0 top-0 overflow-hidden">
											<img src="#image-for-you.jpeg" className="w-[255px] h-[257px] absolute left-[-1px] top-[-1px] object-cover" />
										</div>
										<div className="w-[255px] h-[118px] absolute left-0 top-[257px] overflow-hidden">
											<div className="w-[266px] h-[266px] absolute left-[-6px] top-[-77px] opacity-40">
												<img src="#image-for-you.jpeg" className="w-[274px] h-[237px] absolute left-[-3px] top-[-2px] object-cover" />
											</div>
											<div className="w-[228px] h-[88px] absolute left-3.5 top-4 overflow-hidden">
												<p className="absolute left-px top-0 text-[10px] font-semibold text-left uppercase text-[#ef2f62]">New For You</p>
												<p className="absolute left-px top-5 text-lg font-semibold text-left text-[#fcfcfc]">My New Arrivals</p>
												<p className="w-[197px] absolute left-px top-[47px] text-sm font-semibold text-left text-[#9898a6]">Deine Freunde, Moderat, Sebastián Yatra and more</p>
											</div>
										</div>
										<div className="w-10 h-10 absolute left-[199px] top-[237px] overflow-hidden rounded-[999px] bg-[#fcfcfc]" style={{ boxShadow: '0px 2.200000047683716px 5.5px 0 rgba(0,0,0,0.1)' }}>
											<div className="flex justify-start items-start w-4 h-4 absolute left-3 top-3 overflow-hidden gap-2.5">
												<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
													<path d="M4.0836 14.1878L4.07249 14.1954L4.06181 14.2036C4.03221 14.2264 4.00874 14.2321 3.99134 14.2332C3.97153 14.2344 3.94728 14.2301 3.92186 14.2166C3.86986 14.189 3.83333 14.1358 3.83333 14.0666V1.93327C3.83333 1.86407 3.86987 1.81087 3.92186 1.78328C3.94728 1.76979 3.97153 1.76545 3.99134 1.76668C4.00874 1.76777 4.03221 1.77348 4.06181 1.79625L4.073 1.80486L4.08466 1.81282L12.918 7.84616L12.918 7.84618L12.9226 7.8493C12.9798 7.88739 13 7.93754 13 7.98327C13 8.029 12.9798 8.07916 12.9226 8.11725L12.9226 8.11721L12.9169 8.12112L4.0836 14.1878Z" fill="#171719" stroke="#171719"></path>
												</svg>
											</div>
										</div>
									</div>
									<div className="w-[255px] h-[375px] absolute left-[279px] top-0 overflow-hidden rounded-lg" style={{ filter: 'drop-shadow(0px 8px 28px rgba(0,0,0,0.4))' }}>
										<div className="w-[255px] h-[257px] absolute left-0 top-0 overflow-hidden">
											<img src="rectangle-39.png" className="w-[255px] h-[257px] absolute left-[-1px] top-[-1px] object-cover" />
										</div>
										<div className="w-[255px] h-[118px] absolute left-0 top-[257px] overflow-hidden">
											<div className="w-[266px] h-[266px] absolute left-[-6px] top-[-77px] opacity-40">
												<img src="rectangle-39.png" className="w-[274px] h-[237px] absolute left-[-3px] top-[-2px] object-cover" />
											</div>
											<div className="w-[228px] h-[88px] absolute left-3.5 top-4 overflow-hidden">
												<p className="absolute left-px top-0 text-[10px] font-semibold text-left uppercase text-[#0ff]">New Track for you</p>
												<p className="absolute left-px top-5 text-lg font-semibold text-left text-[#fcfcfc]">Coexist</p>
												<p className="w-[197px] absolute left-px top-[47px] text-sm font-semibold text-left text-[#9898a6]">Album by The XX</p>
											</div>
										</div>
										<div className="w-10 h-10 absolute left-[199px] top-[237px] overflow-hidden rounded-[999px] bg-[#fcfcfc]" style={{ boxShadow: '0px 2.200000047683716px 5.5px 0 rgba(0,0,0,0.1)' }}>
											<div className="flex justify-start items-start w-4 h-4 absolute left-3 top-3 overflow-hidden gap-2.5">
												<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
													<path d="M4.0836 14.1878L4.07249 14.1954L4.06181 14.2036C4.03221 14.2264 4.00874 14.2321 3.99134 14.2332C3.97152 14.2344 3.94728 14.2301 3.92185 14.2166C3.86986 14.189 3.83333 14.1358 3.83333 14.0666V1.93327C3.83333 1.86407 3.86986 1.81087 3.92185 1.78328C3.94728 1.76979 3.97152 1.76545 3.99134 1.76668C4.00874 1.76777 4.03221 1.77348 4.06181 1.79625L4.073 1.80486L4.08466 1.81282L12.918 7.84616L12.918 7.84618L12.9226 7.8493C12.9798 7.88739 13 7.93754 13 7.98327C13 8.029 12.9798 8.07916 12.9226 8.11725L12.9226 8.11721L12.9169 8.12112L4.0836 14.1878Z" fill="#171719" stroke="#171719"></path>
												</svg>
											</div>
										</div>
									</div>
									<div className="w-[255px] h-[375px] absolute left-[558px] top-0 overflow-hidden rounded-lg" style={{ filter: 'drop-shadow(0px 8px 28px rgba(0,0,0,0.4))' }}>
										<div className="w-[255px] h-[257px] absolute left-0 top-0 overflow-hidden">
											<img src="#image-for-you-2.jpeg" className="w-[255px] h-[257px] absolute left-[-1px] top-[-1px] object-cover" />
										</div>
										<div className="w-[255px] h-[118px] absolute left-0 top-[257px] overflow-hidden">
											<div className="w-[266px] h-[266px] absolute left-[-6px] top-[-77px] opacity-40">
												<img src="#image-for-you-2.jpeg" className="w-[274px] h-[237px] absolute left-[-3px] top-[-2px] object-cover" />
											</div>
											<div className="w-[228px] h-[88px] absolute left-3.5 top-4 overflow-hidden">
												<p className="absolute left-px top-0 text-[10px] font-semibold text-left uppercase text-[#ef2f62]">New Album</p>
												<p className="absolute left-px top-5 text-lg font-semibold text-left text-[#fcfcfc]">After Hours</p>
												<p className="w-[197px] absolute left-px top-[47px] text-sm font-semibold text-left text-[#9898a6]">The Weeknd</p>
											</div>
										</div>
										<div className="w-10 h-10 absolute left-[199px] top-[237px] overflow-hidden rounded-[999px] bg-[#fcfcfc]" style={{ boxShadow: '0px 2.200000047683716px 5.5px 0 rgba(0,0,0,0.1)' }}>
											<div className="flex justify-start items-start w-4 h-4 absolute left-3 top-3 overflow-hidden gap-2.5">
												<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
													<path d="M4.08361 14.1878L4.0725 14.1954L4.06182 14.2036C4.03222 14.2264 4.00875 14.2321 3.99136 14.2332C3.97154 14.2344 3.94729 14.2301 3.92187 14.2166C3.86988 14.189 3.83334 14.1358 3.83334 14.0666V1.93327C3.83334 1.86407 3.86988 1.81087 3.92187 1.78328C3.94729 1.76979 3.97154 1.76545 3.99136 1.76668C4.00875 1.76777 4.03222 1.77348 4.06182 1.79625L4.07301 1.80486L4.08467 1.81282L12.918 7.84616L12.918 7.84618L12.9227 7.8493C12.9798 7.88739 13 7.93754 13 7.98327C13 8.029 12.9798 8.07916 12.9227 8.11725L12.9226 8.11721L12.9169 8.12112L4.08361 14.1878Z" fill="#171719" stroke="#171719"></path>
												</svg>
											</div>
										</div>
									</div>
									<div className="w-[255px] h-[375px] absolute left-[837px] top-0 overflow-hidden rounded-lg" style={{ filter: 'drop-shadow(0px 8px 28px rgba(0,0,0,0.4))' }}>
										<div className="w-[255px] h-[257px] absolute left-0 top-0 overflow-hidden">
											<img src="#image-for-you-3.png" className="w-[255px] h-[257px] absolute left-[-1px] top-[-1px] object-cover" />
										</div>
										<div className="w-[255px] h-[118px] absolute left-0 top-[257px] overflow-hidden">
											<div className="w-[266px] h-[266px] absolute left-[-6px] top-[-77px] opacity-40">
												<img src="#image-for-you-3.png" className="w-[274px] h-[237px] absolute left-[-3px] top-[-2px] object-cover" />
											</div>
											<div className="w-[228px] h-[88px] absolute left-3.5 top-4 overflow-hidden">
												<p className="absolute left-px top-0 text-[10px] font-semibold text-left uppercase text-[#ef2f62]">Based on your likes</p>
												<p className="absolute left-px top-5 text-lg font-semibold text-left text-[#fcfcfc]">If You Wait</p>
												<p className="w-[197px] absolute left-px top-[47px] text-sm font-semibold text-left text-[#9898a6]">London Grammar</p>
											</div>
										</div>
										<div className="w-10 h-10 absolute left-[199px] top-[237px] overflow-hidden rounded-[999px] bg-[#fcfcfc]" style={{ boxShadow: '0px 2.200000047683716px 5.5px 0 rgba(0,0,0,0.1)' }}>
											<div className="flex justify-start items-start w-4 h-4 absolute left-3 top-3 overflow-hidden gap-2.5">
												<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
													<path d="M4.08358 14.1878L4.07247 14.1954L4.06179 14.2036C4.03219 14.2264 4.00872 14.2321 3.99132 14.2332C3.97151 14.2344 3.94726 14.2301 3.92184 14.2166C3.86985 14.189 3.83331 14.1358 3.83331 14.0666V1.93327C3.83331 1.86407 3.86985 1.81087 3.92184 1.78328C3.94726 1.76979 3.97151 1.76545 3.99132 1.76668C4.00872 1.76777 4.03219 1.77348 4.06179 1.79625L4.07298 1.80486L4.08464 1.81282L12.918 7.84616L12.918 7.84618L12.9226 7.8493C12.9798 7.88739 13 7.93754 13 7.98327C13 8.029 12.9798 8.07916 12.9226 8.11725L12.9226 8.11721L12.9169 8.12112L4.08358 14.1878Z" fill="#171719" stroke="#171719"></path>
												</svg>
											</div>
										</div>
									</div>
									<div className="w-[255px] h-[375px] absolute left-[1164px] top-0 overflow-hidden rounded-lg" style={{ filter: 'drop-shadow(0px 8px 28px rgba(0,0,0,0.4))' }}>
										<div className="w-[255px] h-[257px] absolute left-0 top-0 overflow-hidden">
											<img src="#bottom-image-for-you.jpeg" className="w-[255px] h-[257px] absolute left-[-1px] top-[-1px] object-cover" />
										</div>
										<div className="w-[255px] h-[118px] absolute left-0 top-[257px] overflow-hidden">
											<div className="w-[266px] h-[266px] absolute left-[-6px] top-[-77px] opacity-40">
												<img src="#bottom-image-for-you.jpeg" className="w-[274px] h-[237px] absolute left-[-3px] top-[-2px] object-cover" />
											</div>
											<div className="w-[228px] h-[88px] absolute left-3.5 top-4 overflow-hidden">
												<p className="absolute left-px top-0 text-[10px] font-semibold text-left uppercase text-[#ef2f62]">Daily updated mix</p>
												<p className="absolute left-px top-5 text-lg font-semibold text-left text-[#fcfcfc]">My Daily Discovery</p>
												<p className="w-[197px] absolute left-px top-[47px] text-sm font-semibold text-left text-[#9898a6]">Songs by new and familiar artists inspired by your listening. Updates every morning.</p>
											</div>
										</div>
										<div className="w-10 h-10 absolute left-[199px] top-[237px] overflow-hidden rounded-[999px] bg-[#fcfcfc]" style={{ boxShadow: '0px 2.200000047683716px 5.5px 0 rgba(0,0,0,0.1)' }}>
											<div className="flex justify-start items-start w-4 h-4 absolute left-3 top-3 overflow-hidden gap-2.5">
												<div className="self-stretch flex-grow relative"></div>
											</div>
										</div>
									</div>
									<div className="w-[255px] h-[375px] absolute left-[1443px] top-0 overflow-hidden rounded-lg" style={{ filter: 'drop-shadow(0px 8px 28px rgba(0,0,0,0.4))' }}>
										<div className="w-[255px] h-[257px] absolute left-0 top-0 overflow-hidden">
											<img src="#bottom-image-for-you-2.png" className="w-[255px] h-[257px] absolute left-[-1px] top-[-1px] object-cover" />
										</div>
										<div className="w-[255px] h-[118px] absolute left-0 top-[257px] overflow-hidden">
											<div className="w-[266px] h-[266px] absolute left-[-6px] top-[-77px] opacity-40">
												<img src="#bottom-image-for-you-2.png" className="w-[274px] h-[237px] absolute left-[-3px] top-[-2px] object-cover" />
											</div>
											<div className="w-[228px] h-[88px] absolute left-3.5 top-4 overflow-hidden">
												<p className="absolute left-px top-0 text-[10px] font-semibold text-left uppercase text-[#ef2f62]">Dig Deeper</p>
												<p className="absolute left-px top-5 text-lg font-semibold text-left text-[#fcfcfc]">Reggaetoneras</p>
												<p className="w-[197px] absolute left-px top-[47px] text-sm font-semibold text-left text-[#9898a6]">Created by TIDAL</p>
											</div>
										</div>
										<div className="w-10 h-10 absolute left-[199px] top-[237px] overflow-hidden rounded-[999px] bg-[#fcfcfc]" style={{ boxShadow: '0px 2.200000047683716px 5.5px 0 rgba(0,0,0,0.1)' }}>
											<div className="flex justify-start items-start w-4 h-4 absolute left-3 top-3 overflow-hidden gap-2.5">
												<div className="self-stretch flex-grow relative"></div>
											</div>
										</div>
									</div>
									<div className="w-[255px] h-[375px] absolute left-[1722px] top-0 overflow-hidden rounded-lg" style={{ filter: 'drop-shadow(0px 8px 28px rgba(0,0,0,0.4))' }}>
										<div className="w-[255px] h-[257px] absolute left-0 top-0 overflow-hidden">
											<img src="#bottom-image-for-you-3.jpeg" className="w-[255px] h-[257px] absolute left-[-1px] top-[-1px] object-cover" />
										</div>
										<div className="w-[255px] h-[118px] absolute left-0 top-[257px] overflow-hidden">
											<div className="w-[266px] h-[266px] absolute left-[-6px] top-[-77px] opacity-40">
												<img src="#bottom-image-for-you-3.jpeg" className="w-[274px] h-[237px] absolute left-[-3px] top-[-2px] object-cover" />
											</div>
											<div className="w-[228px] h-[88px] absolute left-3.5 top-4 overflow-hidden">
												<p className="absolute left-px top-0 text-[10px] font-semibold text-left uppercase text-[#ef2f62]">Behind the music</p>
												<p className="absolute left-px top-5 text-lg font-semibold text-left text-[#fcfcfc]">Songwriter: James Blake</p>
												<p className="w-[197px] absolute left-px top-[47px] text-sm font-semibold text-left text-[#9898a6]">Kendrick Lamar, Jay Rock, Beyoncé and more</p>
											</div>
										</div>
										<div className="w-10 h-10 absolute left-[199px] top-[237px] overflow-hidden rounded-[999px] bg-[#fcfcfc]" style={{ boxShadow: '0px 2.200000047683716px 5.5px 0 rgba(0,0,0,0.1)' }}>
											<div className="flex justify-start items-start w-4 h-4 absolute left-3 top-3 overflow-hidden gap-2.5">
												<div className="self-stretch flex-grow relative"></div>
											</div>
										</div>
									</div>
									<div className="w-[255px] h-[375px] absolute left-[2001px] top-0 overflow-hidden rounded-lg" style={{ filter: 'drop-shadow(0px 8px 28px rgba(0,0,0,0.4))' }}>
										<div className="w-[255px] h-[257px] absolute left-0 top-0 overflow-hidden">
											<img src="#bottom-image-for-you-4.jpeg" className="w-[255px] h-[257px] absolute left-[-1px] top-[-1px] object-cover" />
										</div>
										<div className="w-[255px] h-[118px] absolute left-0 top-[257px] overflow-hidden">
											<div className="w-[266px] h-[266px] absolute left-[-6px] top-[-77px] opacity-40">
												<img src="#bottom-image-for-you-4.jpeg" className="w-[274px] h-[237px] absolute left-[-3px] top-[-2px] object-cover" />
											</div>
											<div className="w-[228px] h-[88px] absolute left-3.5 top-4 overflow-hidden">
												<p className="absolute left-px top-0 text-[10px] font-semibold text-left uppercase text-[#ef2f62]">New Album for you</p>
												<p className="absolute left-px top-5 text-lg font-semibold text-left text-[#fcfcfc]">Club Azur</p>
												<p className="w-[197px] absolute left-px top-[47px] text-sm font-semibold text-left text-[#9898a6]">Album by Kungs</p>
											</div>
										</div>
										<div className="w-10 h-10 absolute left-[199px] top-[237px] overflow-hidden rounded-[999px] bg-[#fcfcfc]" style={{ boxShadow: '0px 2.200000047683716px 5.5px 0 rgba(0,0,0,0.1)' }}>
											<div className="flex justify-start items-start w-4 h-4 absolute left-3 top-3 overflow-hidden gap-2.5">
												<div className="self-stretch flex-grow relative"></div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div className="flex-grow-0 flex-shrink-0 w-[1156px] h-[360px] relative overflow-hidden">
								<div className="w-[1104px] h-[38px] absolute left-8 top-0 overflow-hidden">
									<p className="absolute left-0 top-1.5 text-lg font-semibold text-left text-[#fcfcfc]">Section Title</p>
									<div className="flex justify-center items-center w-6 absolute left-[1104px] top-8 p-1 rounded-[999px] bg-[#1f1f22] border border-[#ebebff]/5">
										<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
											<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
												<path d="M6.00001 13.2L11.2 7.99995L6.00001 2.79995" stroke="#FCFCFC" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
											</svg>
										</div>
									</div>
									<div className="flex justify-center items-center w-6 absolute left-[1048px] top-2 opacity-60 p-1 rounded-[999px] bg-[#1f1f22] border border-[#ebebff]/5">
										<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
											<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
												<path d="M9.99999 2.80005L4.79999 8.00005L9.99999 13.2" stroke="#FCFCFC" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
											</svg>
										</div>
									</div>
								</div>
								<div className="w-[2208px] h-[383px] absolute left-[30px] top-[45px]">
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-px top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-4.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">Blood Sugar Sex Magik (Deluxe Edition)</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Red Hot Chili Peppers</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[1169px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-9.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">Multitude</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Stromae</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[225px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Daily Discovery</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Songs by new and familiar artists inspired by your listening. Updates every morning.</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[1393px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-7.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Mix 1</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Stromae, Angèle, Isaac Delusion and more</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[449px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-2.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Mix 2</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Ghali, Liberato, Coma_Cose and more</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[1617px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-8.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Mix 3</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Lido Pimienta, Romy, Dana Gavanski and more</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[673px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-3.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Mix 4</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Stephanie Beatriz, Kristen Bell, JD McCrary and more</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[1841px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-10.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">Moderat III</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Moderat</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[897px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-5.png" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">In Your Honor</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Foo Fighters</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[2065px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-11.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">In Your Honor</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Foo Fighters</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
								</div>
							</div>
							<div className="flex-grow-0 flex-shrink-0 w-[1156px] h-[360px] relative overflow-hidden">
								<div className="w-[1104px] h-[38px] absolute left-8 top-0 overflow-hidden">
									<p className="absolute left-0 top-1.5 text-lg font-semibold text-left text-[#fcfcfc]">Section Title</p>
									<div className="flex justify-center items-center w-6 absolute left-[1104px] top-8 p-1 rounded-[999px] bg-[#1f1f22] border border-[#ebebff]/5">
										<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
											<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
												<path d="M6.00001 13.2L11.2 7.99995L6.00001 2.79995" stroke="#FCFCFC" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
											</svg>
										</div>
									</div>
									<div className="flex justify-center items-center w-6 absolute left-[1048px] top-2 opacity-60 p-1 rounded-[999px] bg-[#1f1f22] border border-[#ebebff]/5">
										<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
											<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
												<path d="M9.99999 2.80005L4.79999 8.00005L9.99999 13.2" stroke="#FCFCFC" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
											</svg>
										</div>
									</div>
								</div>
								<div className="w-[2208px] h-[383px] absolute left-[30px] top-[45px]">
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-px top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Daily Discovery</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Songs by new and familiar artists inspired by your listening. Updates every morning.</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[1169px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-7.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Mix 1</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Stromae, Angèle, Isaac Delusion and more</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[225px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-2.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Mix 2</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Ghali, Liberato, Coma_Cose and more</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[1393px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-8.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Mix 3</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Lido Pimienta, Romy, Dana Gavanski and more</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[449px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-3.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">My Mix 4</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Stephanie Beatriz, Kristen Bell, JD McCrary and more</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[1617px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-10.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">Moderat III</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Moderat</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[673px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-4.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">Blood Sugar Sex Magik (Deluxe Edition)</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Red Hot Chili Peppers</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[1841px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-11.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">In Your Honor</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Foo Fighters</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[897px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-6.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">Mellon Collie And The Infinite Sadness (Deluxe Edition)</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Greatest Hits</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
									<div className="flex flex-col justify-start items-start w-[200px] absolute left-[2065px] top-0.5 overflow-hidden gap-4">
										<div className="flex-grow-0 flex-shrink-0 w-[200px] h-[200px] relative overflow-hidden rounded-[3px] bg-[#fcfcfc]">
											<img src="#image-thumb-12.jpeg" className="w-[200px] h-[202px] absolute left-[-1px] top-[-3px] object-cover" />
										</div>
										<div className="flex flex-col justify-center items-start flex-grow-0 flex-shrink-0 relative overflow-hidden gap-1">
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]">At Swim</p>
											<p className="flex-grow-0 flex-shrink-0 text-sm font-semibold text-left text-[#fcfcfc]/[0.65]">Lisa Hannigan</p>
											<p className="flex-grow-0 flex-shrink-0 text-[10px] font-semibold text-left text-[#9898a6]">LABEL</p>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div className="w-[1200px] h-[70px] absolute left-0 top-0 overflow-hidden">
							<div className="flex justify-start items-center w-[389px] h-10 absolute left-[706px] top-[23px] overflow-hidden gap-2.5 p-2.5 rounded-xl bg-[#1f1f22] border border-[#ebebff]/5">
								<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
									<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
										<path d="M11.5927 12.0172L11.2833 11.7078L10.9356 11.9735C10.0104 12.6803 8.85485 13.1 7.60001 13.1C4.56244 13.1 2.10001 10.6375 2.10001 7.59998C2.10001 4.56241 4.56244 2.09998 7.60001 2.09998C10.6375 2.09998 13.1 4.56241 13.1 7.59998C13.1 8.85497 12.6803 10.0105 11.9733 10.9359L11.7076 11.2835L12.017 11.593L14.2118 13.7878L14.2118 13.7878C14.3289 13.905 14.3289 14.095 14.2118 14.2121C14.0947 14.3292 13.9047 14.3292 13.7876 14.2121L11.5927 12.0172ZM7.60001 2.69998C4.89381 2.69998 2.70001 4.89378 2.70001 7.59998C2.70001 10.3062 4.89381 12.5 7.60001 12.5C10.3062 12.5 12.5 10.3062 12.5 7.59998C12.5 4.89378 10.3062 2.69998 7.60001 2.69998Z" fill="#FCFCFC" stroke="#FCFCFC"></path>
									</svg>
								</div>
								<p className="flex-grow w-[343px] text-sm text-left text-[#fcfcfc]">Search</p>
							</div>
							<div className="flex justify-center items-center absolute left-[1107px] top-[23px] p-3 rounded-[999px] bg-[#1f1f22] border border-[#ebebff]/5">
								<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
									<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
										<path d="M9.99999 2.80005L4.79999 8.00005L9.99999 13.2" stroke="#FCFCFC" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
									</svg>
								</div>
							</div>
							<div className="flex justify-center items-center absolute left-[52px] top-[15px] p-3 rounded-[999px] bg-[#1f1f22] border border-[#ebebff]/5">
								<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
									<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
										<path d="M10 2.80005L4.8 8.00005L10 13.2" stroke="#FCFCFC" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
									</svg>
								</div>
							</div>
							<div className="flex justify-center items-center absolute left-[140px] top-[55px] opacity-60 p-3 rounded-[999px] bg-[#1f1f22] border border-[#ebebff]/5">
								<div className="flex justify-start items-start flex-grow-0 flex-shrink-0 w-4 h-4 relative overflow-hidden gap-2.5">
									<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" className="self-stretch flex-grow relative" preserveAspectRatio="none">
										<path d="M6 13.2001L11.2 8.00005L6 2.80005" stroke="#FCFCFC" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path>
									</svg>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
