export default function Loading(status) {
	if (status == 'loading') {
		return (
			<>
				<Head>
					<title>Music</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="w-full">loading</main>
			</>
		);
	}

	if (status == 'unauthenticated') {
		router.push('/auth/signin');
		return (
			<>
				<Head>
					<title>Music</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="w-full"></main>
			</>
		);
	}
}
